# -*- coding: utf-8 -*-
"""Officially verified Kiwoom realtime FIDs used by shadow mode."""

# KOA StudioSA 2.34 Real Type "주식체결"; installed koa_devguide.xml
# GetCommRealData example at lines 629-652 (CP949 source).
REALTIME_EXECUTION_TIME_FID = 20  # 체결시간
REALTIME_CURRENT_PRICE_FID = 10  # 현재가
REALTIME_CUMULATIVE_VOLUME_FID = 13  # 누적거래량
REALTIME_TRADE_VOLUME_FID = 15  # 체결량 (매도 -, 매수 +)
REALTIME_CHANGE_RATE_FID = 12  # 등락율
REALTIME_OPEN_PRICE_FID = 16  # 시가
REALTIME_HIGH_PRICE_FID = 17  # 고가
REALTIME_LOW_PRICE_FID = 18  # 저가
REALTIME_PREVIOUS_DAY_VOLUME_RATE_FID = 30  # 전일거래량 대비(비율)
REALTIME_EXECUTION_STRENGTH_FID = 228  # 체결강도
REALTIME_EXECUTION_TYPE = "주식체결"

REALTIME_SHADOW_FIDS = (
    REALTIME_EXECUTION_TIME_FID,
    REALTIME_CURRENT_PRICE_FID,
    REALTIME_CUMULATIVE_VOLUME_FID,
    REALTIME_TRADE_VOLUME_FID,
    REALTIME_CHANGE_RATE_FID,
    REALTIME_OPEN_PRICE_FID,
    REALTIME_HIGH_PRICE_FID,
    REALTIME_LOW_PRICE_FID,
    REALTIME_PREVIOUS_DAY_VOLUME_RATE_FID,
    REALTIME_EXECUTION_STRENGTH_FID,
)
