# -*- coding: utf-8 -*-
"""Officially verified Kiwoom realtime FIDs used by shadow mode."""

# KOA StudioSA 2.34 Real Type "주식체결"; installed koa_devguide.xml
# GetCommRealData example at lines 629-652 (CP949 source).
REALTIME_EXECUTION_TIME_FID = 20  # 체결시간
REALTIME_CURRENT_PRICE_FID = 10  # 현재가
REALTIME_CUMULATIVE_VOLUME_FID = 13  # 누적거래량
REALTIME_TRADE_VOLUME_FID = 15  # 체결량 (매도 -, 매수 +)
REALTIME_CHANGE_RATE_FID = 12  # 등락율
REALTIME_OPEN_PRICE_FID = 16  # 시가
REALTIME_HIGH_PRICE_FID = 17  # 고가
REALTIME_LOW_PRICE_FID = 18  # 저가
REALTIME_PREVIOUS_DAY_VOLUME_RATE_FID = 30  # 전일거래량 대비(비율)
REALTIME_EXECUTION_STRENGTH_FID = 228  # 체결강도
REALTIME_EXECUTION_TYPE = "주식체결"

REALTIME_SHADOW_FIDS = (
    REALTIME_EXECUTION_TIME_FID,
    REALTIME_CURRENT_PRICE_FID,
    REALTIME_CUMULATIVE_VOLUME_FID,
    REALTIME_TRADE_VOLUME_FID,
    REALTIME_CHANGE_RATE_FID,
    REALTIME_OPEN_PRICE_FID,
    REALTIME_HIGH_PRICE_FID,
    REALTIME_LOW_PRICE_FID,
    REALTIME_PREVIOUS_DAY_VOLUME_RATE_FID,
    REALTIME_EXECUTION_STRENGTH_FID,
)

# Installed KOA StudioSA 2.34 ``koarealtime.dat`` Real Type
# "주식호가잔량" plus the installed KOAStudioSA FID dictionary.
# These remain separate from REALTIME_SHADOW_FIDS because they feed only the
# isolated Mock Validation market-data stream.
REALTIME_ORDERBOOK_TYPE = "주식호가잔량"
REALTIME_ORDERBOOK_TIME_FID = 21  # 호가시간
REALTIME_ASK_PRICE_FIDS = tuple(range(41, 51))  # 매도호가 1~10
REALTIME_BID_PRICE_FIDS = tuple(range(51, 61))  # 매수호가 1~10
REALTIME_ASK_QTY_FIDS = tuple(range(61, 71))  # 매도호가수량 1~10
REALTIME_BID_QTY_FIDS = tuple(range(71, 81))  # 매수호가수량 1~10
REALTIME_TOTAL_ASK_QTY_FID = 121  # 매도호가총잔량
REALTIME_TOTAL_BID_QTY_FID = 125  # 매수호가총잔량
REALTIME_ORDERBOOK_FIDS = (
    REALTIME_ORDERBOOK_TIME_FID,
    *REALTIME_ASK_PRICE_FIDS,
    *REALTIME_BID_PRICE_FIDS,
    *REALTIME_ASK_QTY_FIDS,
    *REALTIME_BID_QTY_FIDS,
    REALTIME_TOTAL_ASK_QTY_FID,
    REALTIME_TOTAL_BID_QTY_FID,
)
